
package lt.viko.eif.rcepauskas.server;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HappyServiceImplService", targetNamespace = "http://server.rcepauskas.eif.viko.lt/", wsdlLocation = "http://localhost:5050/HappyService/BeHappy?wsdl")
public class HappyServiceImplService
    extends Service
{

    private final static URL HAPPYSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException HAPPYSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName HAPPYSERVICEIMPLSERVICE_QNAME = new QName("http://server.rcepauskas.eif.viko.lt/", "HappyServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5050/HappyService/BeHappy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HAPPYSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        HAPPYSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public HappyServiceImplService() {
        super(__getWsdlLocation(), HAPPYSERVICEIMPLSERVICE_QNAME);
    }

    public HappyServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HAPPYSERVICEIMPLSERVICE_QNAME, features);
    }

    public HappyServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, HAPPYSERVICEIMPLSERVICE_QNAME);
    }

    public HappyServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HAPPYSERVICEIMPLSERVICE_QNAME, features);
    }

    public HappyServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HappyServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HappyService
     */
    @WebEndpoint(name = "HappyServiceImplPort")
    public HappyService getHappyServiceImplPort() {
        return super.getPort(new QName("http://server.rcepauskas.eif.viko.lt/", "HappyServiceImplPort"), HappyService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HappyService
     */
    @WebEndpoint(name = "HappyServiceImplPort")
    public HappyService getHappyServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.rcepauskas.eif.viko.lt/", "HappyServiceImplPort"), HappyService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HAPPYSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw HAPPYSERVICEIMPLSERVICE_EXCEPTION;
        }
        return HAPPYSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
