
package lt.viko.eif.rcepauskas.server;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HappyService", targetNamespace = "http://server.rcepauskas.eif.viko.lt/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HappyService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHappyness", targetNamespace = "http://server.rcepauskas.eif.viko.lt/", className = "lt.viko.eif.rcepauskas.server.GetHappyness")
    @ResponseWrapper(localName = "getHappynessResponse", targetNamespace = "http://server.rcepauskas.eif.viko.lt/", className = "lt.viko.eif.rcepauskas.server.GetHappynessResponse")
    @Action(input = "http://server.rcepauskas.eif.viko.lt/HappyService/getHappynessRequest", output = "http://server.rcepauskas.eif.viko.lt/HappyService/getHappynessResponse")
    public String getHappyness(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
